### ISSUE TITLE
Error in Makefile

### ISSUE THREAD

**Issue by kaiiyer** [TomorrowSOC/OpenUB#1]
No file named mypy in core directory
The output is attached below:
![image](https://user-images.githubusercontent.com/24914913/71241271-3ce17680-2331-11ea-906b-2ef9b6da9c9f.png)

**Comment by Jovonni** [comment]
Hm, let me take a look at this today. Try the dev branch for now. I’ll fix that, it’s small. Let me know if the dev branch has the same error

**Comment by kaiiyer** [comment]
@Jovonni I've seen that the dashboard shows random static values instead of showing the results of anomalies. I know the project is under development but would like to know if we can use LSTM Autoencoder for anomaly detection and send the results to web app from python scripts using Flask

**Comment by Jovonni** [comment]
Never mind, you forked it. I have a handful of updates to merge too. Let's chat so you can see the direction set. Im sure you have many ideas.

**Comment by Jovonni** [comment]
Never mind, you forked it. I have a handful of updates to merge too. Let's chat so you can see the direction set. Im sure you have many ideas. I already have working examples of several tensorflow and sklearn models running, and you see the model loader i started on. Its just writing files or now, just so we can support users uploading their own models.

Looking forward to it. I see the PR too, I'll merge the main dev branch as well soon. Send me your email, etc

**Comment by kaiiyer** [comment]
Thank you for the response. My mail address is kaiiyer47@yahoo.in
